-- MySQL Script generated by MySQL Workbench
-- 09/09/16 09:12:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ot` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ot` ;

-- -----------------------------------------------------
-- Table `ot`.`base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`base` (
  `idbase` INT(11) NOT NULL,
  `nombre_base` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbase`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ot`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`especialidad` (
  `idespecialidad` INT(11) NOT NULL,
  `nombre_especialidad` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ot`.`itemc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`itemc` (
  `iditemc` INT(11) NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `unidad` VARCHAR(10) NULL DEFAULT NULL,
  `hrdisp` INT(11) NULL DEFAULT NULL,
  `basedisp` INT(11) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `fechap` DATE NULL DEFAULT NULL,
  `idproceso` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `id_UNIQUE` (`iditemc` ASC),
  UNIQUE INDEX `item` (`item` ASC),
  PRIMARY KEY (`iditemc`, `item`))
ENGINE = InnoDB
AUTO_INCREMENT = 578
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ot`.`itemf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`itemf` (
  `iditemf` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `tipo` INT(11) NOT NULL,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `fechap` DATE NULL,
  `idproceso` INT(11) NULL DEFAULT NULL,
  `itemc_iditemc` INT(11) NOT NULL,
  `itemc_item` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `codigo` (`codigo` ASC),
  UNIQUE INDEX `id` (`iditemf` ASC),
  PRIMARY KEY (`iditemf`, `codigo`),
  INDEX `fk_itemf_itemc1_idx` (`itemc_iditemc` ASC, `itemc_item` ASC),
  CONSTRAINT `fk_itemf_itemc1`
    FOREIGN KEY (`itemc_iditemc` , `itemc_item`)
    REFERENCES `ot`.`itemc` (`iditemc` , `item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 737
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ot`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`municipio` (
  `idpoblado` INT(11) NOT NULL,
  `cddpto` VARCHAR(2) NOT NULL,
  `cdmunicipio` VARCHAR(5) NOT NULL,
  `cdcntrpoblado` VARCHAR(8) NOT NULL,
  `departamento` VARCHAR(60) NOT NULL,
  `municipio` VARCHAR(50) NOT NULL,
  `centropoblado` VARCHAR(50) NOT NULL,
  `tipocentropoblado` VARCHAR(50) NOT NULL,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  PRIMARY KEY (`idpoblado`))
ENGINE = InnoDB
AUTO_INCREMENT = 8017
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ot`.`tipo_ot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`tipo_ot` (
  `idtipo_ot` INT(11) NOT NULL,
  `nombre_tipo_ot` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_ot`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ot`.`OT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`OT` (
  `idOT` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_ot` VARCHAR(50) NULL DEFAULT NULL,
  `numero_sap` VARCHAR(45) NULL DEFAULT NULL,
  `actividad` VARCHAR(500) NULL DEFAULT NULL,
  `justificacion` VARCHAR(600) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `locacion` VARCHAR(60) NULL DEFAULT NULL,
  `abscisa` VARCHAR(45) NULL DEFAULT NULL,
  `zona` VARCHAR(45) NULL,
  `json` VARCHAR(8000) NULL DEFAULT NULL,
  `base_idbase` INT(11) NOT NULL,
  `municipio_idpoblado` INT(11) NOT NULL,
  `tipo_ot_idtipo_ot` INT(11) NOT NULL,
  `especialidad_idespecialidad` INT(11) NOT NULL,
  PRIMARY KEY (`idOT`),
  UNIQUE INDEX `numero_sap_UNIQUE` (`numero_sap` ASC),
  UNIQUE INDEX `nombre_ot_UNIQUE` (`nombre_ot` ASC),
  INDEX `fk_OT_base1_idx` (`base_idbase` ASC),
  INDEX `fk_OT_municipio1_idx` (`municipio_idpoblado` ASC),
  INDEX `fk_OT_tipo_ot1_idx` (`tipo_ot_idtipo_ot` ASC),
  INDEX `fk_OT_especialidad1_idx` (`especialidad_idespecialidad` ASC),
  CONSTRAINT `fk_OT_base1`
    FOREIGN KEY (`base_idbase`)
    REFERENCES `ot`.`base` (`idbase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OT_especialidad1`
    FOREIGN KEY (`especialidad_idespecialidad`)
    REFERENCES `ot`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OT_municipio1`
    FOREIGN KEY (`municipio_idpoblado`)
    REFERENCES `ot`.`municipio` (`idpoblado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OT_tipo_ot1`
    FOREIGN KEY (`tipo_ot_idtipo_ot`)
    REFERENCES `ot`.`tipo_ot` (`idtipo_ot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ot`.`tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`tarifa` (
  `idtarifa` INT(11) NOT NULL,
  `tarifa` DOUBLE NULL DEFAULT NULL,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `fechap` DATE NULL DEFAULT NULL,
  `salario` DOUBLE NOT NULL,
  `estado_salario` TINYINT(1) NOT NULL,
  `idproceso` INT(11) NULL DEFAULT NULL,
  `periodo_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `estado_tarifa` TINYINT(1) NULL,
  `itemf_iditemf` INT(11) UNSIGNED NOT NULL,
  `itemf_codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idtarifa`),
  INDEX `fk_tarifa_itemf1_idx` (`itemf_iditemf` ASC, `itemf_codigo` ASC),
  CONSTRAINT `fk_tarifa_itemf1`
    FOREIGN KEY (`itemf_iditemf` , `itemf_codigo`)
    REFERENCES `ot`.`itemf` (`iditemf` , `codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1342
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ot`.`tarifas_gv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`tarifas_gv` (
  `idtarifa_gv` INT(11) NOT NULL,
  `destino` VARCHAR(70) NOT NULL,
  `alojamiento` DOUBLE NOT NULL,
  `alimentacion` DOUBLE NOT NULL,
  `transporte` DOUBLE NOT NULL,
  `miscelanios` DOUBLE NOT NULL,
  `terminal_aerea` DOUBLE NOT NULL,
  `terminal_terrestre` DOUBLE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `idgrupo_tarifas_gv` INT(11) NOT NULL,
  PRIMARY KEY (`idtarifa_gv`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ot`.`tarea_ot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`tarea_ot` (
  `idtarea_ot` INT NOT NULL AUTO_INCREMENT,
  `nombre_tarea` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `valor_recursos` DOUBLE NULL,
  `valor_tarea_ot` DOUBLE NULL,
  `json_indirectos` VARCHAR(3000) NULL,
  `json_recursos` VARCHAR(5000) NULL,
  `json_viaticos` VARCHAR(3000) NULL,
  `json_horas_extra` VARCHAR(3000) NULL,
  `json_reembolsables` VARCHAR(3000) NULL,
  `json_raciones` VARCHAR(400) NULL,
  `OT_idOT` INT(11) NOT NULL,
  PRIMARY KEY (`idtarea_ot`),
  INDEX `fk_tarea_ot_OT1_idx` (`OT_idOT` ASC),
  CONSTRAINT `fk_tarea_ot_OT1`
    FOREIGN KEY (`OT_idOT`)
    REFERENCES `ot`.`OT` (`idOT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ot`.`item_tarea_ot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`item_tarea_ot` (
  `iditem_tarea_ot` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `duracion` INT NULL,
  `unidad` VARCHAR(45) NULL,
  `tarifa` DOUBLE NULL,
  `fecha_agregado` DATETIME NULL,
  `valor_plan` DOUBLE NULL,
  `itemf_iditemf` INT(11) UNSIGNED NOT NULL,
  `itemf_codigo` VARCHAR(20) NOT NULL,
  `tarea_ot_idtarea_ot` INT NOT NULL,
  PRIMARY KEY (`iditem_tarea_ot`),
  INDEX `fk_itemf_has_tarea_ot_tarea_ot1_idx` (`tarea_ot_idtarea_ot` ASC),
  INDEX `fk_itemf_has_tarea_ot_itemf1_idx` (`itemf_iditemf` ASC, `itemf_codigo` ASC),
  CONSTRAINT `fk_itemf_has_tarea_ot_itemf1`
    FOREIGN KEY (`itemf_iditemf` , `itemf_codigo`)
    REFERENCES `ot`.`itemf` (`iditemf` , `codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemf_has_tarea_ot_tarea_ot1`
    FOREIGN KEY (`tarea_ot_idtarea_ot`)
    REFERENCES `ot`.`tarea_ot` (`idtarea_ot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ot`.`repote_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`repote_diario` (
  `idrepote_diario` INT NOT NULL AUTO_INCREMENT,
  `fecha_reporte` DATE NULL,
  `json` VARCHAR(5000) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idrepote_diario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ot`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`persona` (
  `identificacion` VARCHAR(20) NOT NULL,
  `nombre_completo` VARCHAR(150) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ot`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `serial` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`idequipo`, `serial`),
  UNIQUE INDEX `serial_UNIQUE` (`serial` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ot`.`recurso_ot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`recurso_ot` (
  `idrecurso_ot` INT NOT NULL AUTO_INCREMENT,
  `tipo_recurso` VARCHAR(45) NULL,
  `nombre_ot` VARCHAR(45) NULL,
  `persona_identificacion` VARCHAR(20) NOT NULL,
  `OT_idOT` INT(11) NULL,
  `itemf_iditemf` INT(11) UNSIGNED NOT NULL,
  `itemf_codigo` VARCHAR(20) NOT NULL,
  `equipo_idequipo` INT NOT NULL,
  `equipo_serial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecurso_ot`),
  INDEX `fk_recurso_ot_persona1_idx` (`persona_identificacion` ASC),
  INDEX `fk_recurso_ot_OT1_idx` (`OT_idOT` ASC),
  INDEX `fk_recurso_ot_itemf1_idx` (`itemf_iditemf` ASC, `itemf_codigo` ASC),
  INDEX `fk_recurso_ot_equipo1_idx` (`equipo_idequipo` ASC, `equipo_serial` ASC),
  CONSTRAINT `fk_recurso_ot_persona1`
    FOREIGN KEY (`persona_identificacion`)
    REFERENCES `ot`.`persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recurso_ot_OT1`
    FOREIGN KEY (`OT_idOT`)
    REFERENCES `ot`.`OT` (`idOT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recurso_ot_itemf1`
    FOREIGN KEY (`itemf_iditemf` , `itemf_codigo`)
    REFERENCES `ot`.`itemf` (`iditemf` , `codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recurso_ot_equipo1`
    FOREIGN KEY (`equipo_idequipo` , `equipo_serial`)
    REFERENCES `ot`.`equipo` (`idequipo` , `serial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ot`.`recurso_reporte_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ot`.`recurso_reporte_dia` (
  `idrecurso_reporte_dia` INT NOT NULL AUTO_INCREMENT,
  `repote_diario_idrepote_diario` INT NOT NULL,
  `recurso_ot_idrecurso_ot` INT NOT NULL,
  PRIMARY KEY (`idrecurso_reporte_dia`),
  INDEX `fk_recurso_reporte_dia_repote_diario1_idx` (`repote_diario_idrepote_diario` ASC),
  INDEX `fk_recurso_reporte_dia_recurso_ot1_idx` (`recurso_ot_idrecurso_ot` ASC),
  CONSTRAINT `fk_recurso_reporte_dia_repote_diario1`
    FOREIGN KEY (`repote_diario_idrepote_diario`)
    REFERENCES `ot`.`repote_diario` (`idrepote_diario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recurso_reporte_dia_recurso_ot1`
    FOREIGN KEY (`recurso_ot_idrecurso_ot`)
    REFERENCES `ot`.`recurso_ot` (`idrecurso_ot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
